import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e0f7fa', 
    paddingHorizontal: 24,
    paddingVertical: 50,
  },
  logoContainer: {
    marginBottom: 32,
    alignItems: 'center',
  },
  inputMessage: {
    height: '50%',
    textAlignVertical: 'top',
  },
  icon: {
    alignItems: 'flex-end',
    flex: 1,
  },
  commentItem: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  commentAuthor: {
    fontWeight: '700',
    //color: '#00695c', 
    marginBottom: 4,
    fontSize: 16,
  },
  commentText: {
    fontSize: 15,
    //color: '#37474f',
    //lineHeight: 22,
  },
  modalComments: {
    backgroundColor: '#ffffff',
    margin: 16,
    padding: 0,
    borderRadius: 20,
    //elevation: 10,
    //flex: 1,
    //maxHeight: '85%',
  },
  headerModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    paddingBottom: 12,
  },
  iconButton: {
    marginLeft: 8,
  },
  text: {
    fontSize: 34,
    fontWeight: '800',
    color: '#00695c',
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: 0.8,
    lineHeight: 40,
  },
  subtitle: {
    fontSize: 17,
    color: '#546e7a',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 24,
  },
  inputStyle: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginBottom: 18,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
  },
  button: {
    width: '100%',
    paddingVertical: 14,
    backgroundColor: '#00b894', 
    borderRadius: 16,
    marginBottom: 18,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    justifyContent: 'center',
  },
  buttonLabel: {
    fontWeight: '700',
    fontSize: 17,
    color: '#ffffff',
  },
  textRedirect: {
    fontSize: 16,
    color: '#00838f',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 12,
    textDecorationLine: 'underline',
  },
  snackbar: {
    borderRadius: 12,
    marginBottom: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  containerActivity: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerProfile: {
    position: 'absolute',
    top: 40,
    right: 20,
    color: '#00695c',
  },
  textProfile: {
    position: 'absolute',
    top: 70,
    left: 20,
  },
  containerImage: {
    alignItems: 'center',
    marginVertical: 20,
  },
  containerIcons: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 12,
  },
  containerB: {
    flex: 1,
    backgroundColor: '#e0f7fa',
    justifyContent: 'center',
    padding: 25,
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 20,
    alignItems: 'center',
    width: '100%',
    maxWidth: 450,
    top: -65,

  },
  title: {
    fontSize: 30,
    fontWeight: '800',
    color: '#00695c',
    marginBottom: 18,
    textAlign: 'center',
    letterSpacing: 0.6,
    lineHeight: 36,
  },
  attempts: {
    fontSize: 19,
    fontWeight: '700',
    color: '#00838f',
    marginBottom: 22,
  },
  message: {
    fontSize: 19,
    textAlign: 'center',
    marginBottom: 30,
    color: '#37474f',
    lineHeight: 26,
    paddingHorizontal: 12,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  input: {
    borderWidth: 2,
    borderColor: '#81d4fa',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    fontSize: 19,
    textAlign: 'center',
    fontWeight: '700',
    color: '#00695c',
    backgroundColor: '#f1f8e9',
    flex: 1,
    maxWidth: 130,
  },
  guessButton: {
    backgroundColor: '#00b894',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 16,
    minWidth: 110,
    alignItems: 'center',
    justifyContent: 'center',
  },
  restartButton: {
    backgroundColor: '#00b894',
    paddingHorizontal: 26,
    paddingVertical: 16,
    borderRadius: 16,
    minWidth: 190,
    alignItems: 'center',
    marginTop: 12,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
  },
  modal: {
    backgroundColor: '#ffffff',
    padding: 24,
    marginHorizontal: 20,
    borderRadius: 16,
    gap: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
  },
  modalContainer: {
    backgroundColor: 'white',
    margin: 20,
    padding: 24,
    borderRadius: 20,
    elevation: 8,
  },
  emailText: {
    marginBottom: 18,
    textAlign: 'center',
    color: '#555',
    fontSize: 16,
  },
  inputModal: {
    marginBottom: 18,
  },
  saveButton: {
    marginTop: 14,
  },
  fab: {
    position: 'absolute',
    bottom: 32,
    left: 32,
  },
  fab2: {
    position: 'absolute',
    bottom: 32,
    right: 32,
  },
  headerHome: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
    marginBottom: 24,
  },
  iconSingOut: {
    marginTop: 28,
    alignItems: 'center',
  },
});